# answer = """{
# "question": "What are the 3 differences between a relational database and a data warehouse?",
# "score": 5,
# "reasoning": "The student mentions two clear differences between relational databases and data warehouses:
# 1. Purpose: The student correctly states that relational databases are used for Online Transactional Processing (OLTP) but can also be used for other purposes such as Data Warehousing, while data warehouses are the second stage where data is no longer queried in large quantities and has been aggregated and denormalized for analysis.
# 2. Data Structure: Although the student does not explicitly mention the data structure difference (relational databases use a structured schema with tables, rows, and columns requiring a predefined schema, while data warehouses organize data in a format optimal for querying and analysis), they do imply this difference by stating that relational databases have complicated tables and joins due to normalization, which is done to reduce redundant data and save storage space. Data warehouses, on the other hand, denormalize data for efficient querying and analysis.
#
# Therefore, the student's answer meets the requirements of the rubric (mentioning two or more differences between relational databases and data warehouses with correct and concise explanations)."
# }"""
#
# # Evaluate the corrected string
# eval(answer)
import json

val = """[{"question": "What are the challenges in data volume when implementing Big Data?", "student_answer": "", "evaluation_level": "Not Answered", "evaluation": "The student did not provide an answer to this question."},{"question": "What are the challenges in data velocity when implementing Big Data?", "student_answer": "", "evaluation_level": "Not Answered", "evaluation": "The student did not provide an answer to this question."},{"question": "What are the challenges in data variety when implementing Big Data?", "student_answer": "", "evaluation_level": "Not Answered", "evaluation": "The student did not provide an answer to this question."},{"question": "What are the challenges in data veracity when implementing Big Data?", "student_answer": "Big data has the characteristic of veracity which means accurate and valid, this becomes vulnerable because it is necessary to analyze many things to produce the right decision.", "evaluation_level": "Partially Correct", "evaluation": "The student correctly identified veracity as a characteristic of big data, but the explanation is incomplete. The supporting theory mentions data quality and cleanliness as a challenge, which is related to veracity."},{"question": "What are the challenges in data complexity when implementing Big Data?", "student_answer": "", "evaluation_level": "Not Answered", "evaluation": "The student did not provide an answer to this question."},{"question": "What are the challenges in data security when implementing Big Data?", "student_answer": "", "evaluation_level": "Not Answered", "evaluation": "The student did not provide an answer to this question."},{"question":styleType: "What are the challenges in data governance when implementing Big Data?", "student_answer": "", "evaluation_level": "Not Answered", "evaluation": "The student did not provide an answer to this question."},{"question": "What are the challenges in data integration when implementing Big Data?", "student_answer": "", "evaluation_level": "Not Answered", "evaluation": "The student did not provide an answer to this question."},{"question": "What are the challenges in data processing when implementing Big Data?", "student_answer": "", "evaluation_level": "Not Answered", "evaluation": "The student did not provide an answer to this question."},{"question": "What are the challenges in data storage when implementing Big Data?", "student_answer": "", "evaluation_level": "Not Answered", "evaluation": "The student did not provide an answer to this question."}]"""

print(eval(val))